-- Create fcm_tokens table if it doesn't exist
CREATE TABLE IF NOT EXISTS fcm_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token VARCHAR(255) NOT NULL UNIQUE,
    device_type VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_fcm_token_user FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Create app_notifications table
CREATE TABLE IF NOT EXISTS app_notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    body TEXT NOT NULL,
    type VARCHAR(50),
    related_entity_id VARCHAR(255),
    is_read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_app_notification_user FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Indexes for performance
CREATE INDEX idx_fcm_token_user ON fcm_tokens(user_id);
CREATE INDEX idx_app_notification_user ON app_notifications(user_id);
CREATE INDEX idx_app_notification_is_read ON app_notifications(is_read);
